import Post1a from '../src/resources/StoryPosts/post1a.jpg';
const userStory=[
    {
        id:1,
        username:'silverswan131',
        profile:'https://randomuser.me/api/portraits/med/men/75.jpg'
    },
    {
        id:8,
        username:'lois Ramoos',
        profile:'https://images.unsplash.com/photo-1493612276216-ee3925520721?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cmFuZG9tfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80'
    },
    {
        id:2,
        username:'marhoward',
        profile:'https://images.unsplash.com/photo-1496449903678-68ddcb189a24?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8cmFuZG9tfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80'
    },
    {
        id:3,
        username:'vivan_scott',
        profile:'https://images.unsplash.com/photo-1489533119213-66a5cd877091?ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8cmFuZG9tfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=60'
    },
    {
        id:4,
        username:'maxy__21',
        profile:'https://randomuser.me/api/portraits/med/men/91.jpg'
    },
    {
        id:5,
        username:'charlie_puth',
        profile:'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHJhbmRvbXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60'
    },
    {
        id:6,
        username:'gordenliam',
        profile:'https://randomuser.me/api/portraits/med/men/73.jpg'
    },
    {
        id:7,
        username:'marsha11',
        profile:'https://randomuser.me/api/portraits/med/men/17.jpg'
    },
    
    {
        id:9,
        username:'jessica789brown',
        profile:'https://randomuser.me/api/portraits/med/women/55.jpg'
    },
    {
        id:10,
        username:'carmendean',
        profile:'https://randomuser.me/api/portraits/med/women/25.jpg'
    },
    {
        id:11,
        username:'jessie_franklin',
        profile:'https://randomuser.me/api/portraits/med/men/80.jpg'
    },
    {
        id:12,
        username:'franzis_Perez',
        profile:'https://randomuser.me/api/portraits/med/men/78.jpg'
    },
    {
        id:13,
        username:'heather_day',
        profile:'https://randomuser.me/api/portraits/med/women/49.jpg'
    },
    {
        id:14,
        username:'devonkim__',
        profile:'https://randomuser.me/api/portraits/med/men/40.jpg'
    },
    {
        id:15,
        username:'MarianNR',
        profile:'https://randomuser.me/api/portraits/med/women/61.jpg'
    }

]


const StoryData=[
    {
        storyIndex:1,
        userProfile:{
            username:'silverswan131',
            profilePicture:'https://randomuser.me/api/portraits/med/men/75.jpg',
        },
        storyThumbnail:Post1a,
        story:[
            {
            id:1,
            type:'image',
            source:Post1a,
            time:'23h',
            reply:false
            },
        ] 
    },
    {
        storyIndex:2,
        userProfile:{
            username:'lois Ramoos',
            profilePicture:'https://images.unsplash.com/photo-1493612276216-ee3925520721?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cmFuZG9tfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80',
        },
        storyThumbnail:Post1a,
        story:[
            {
            id:1,
            type:'image',
            source:Post1a,
            time:'9h',
            reply:false
            }
        ] 
    },
    {
        storyIndex:3,
        userProfile:{
            username:'marhoward',
            profilePicture:'https://images.unsplash.com/photo-1496449903678-68ddcb189a24?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8cmFuZG9tfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80',
        },
        storyThumbnail:Post1a,
        story:[
            {
            id:1,
            type:'image',
            source:Post1a,
            time:'11h',
            reply:false
            },

        ] 
    },
    {
        storyIndex:4,
        userProfile:{
            username:'vivan_scott',
            profilePicture:'https://images.unsplash.com/photo-1489533119213-66a5cd877091?ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8cmFuZG9tfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=300&q=60'
        },
        storyThumbnail:Post1a,
        story:[
            {
            id:1,
            type:'image',
            source:Post1a,
            time:'4h',
            reply:true
            },
        ]
    },
    {
        storyIndex:5,
        userProfile:{
            username:'maxy__21',
            profilePicture:'https://randomuser.me/api/portraits/med/women/61.jpg',
        },
        storyThumbnail:Post1a,
        story:[
            {
            id:1,
            type:'image',
            source:Post1a,
            time:'7h',
            },
        ] 
    },
    {
        storyIndex:6,
        userProfile:{
            username:'charlie_puth',
            profilePicture:'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHJhbmRvbXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
        },
        storyThumbnail:Post1a,
        story:[
            {
            id:1,
            type:'image',
            source:Post1a,
            time:'10h'
            },
        ] 
    },
    {
        storyIndex:7,
        userProfile:{
            username:'gordenliam',
            profilePicture:'https://randomuser.me/api/portraits/med/men/73.jpg',
        },
        storyThumbnail:Post1a,
        story:[
            {
            id:1,
            type:'image',
            source:Post1a,
            time:'12h'
            },
        ] 
    },
    {
        storyIndex:8,
        userProfile:{
            username:'jessica789brown',
            profilePicture:'https://randomuser.me/api/portraits/med/women/55.jpg',
        },
        storyThumbnail:Post1a,
        story:[
            {
            id:1,
            type:'image',
            source:Post1a,
            time:'8h'
            },
        ] 
    },
    {
        storyIndex:9,
        userProfile:{
            username:'carmendean',
            profilePicture:'https://randomuser.me/api/portraits/med/women/25.jpg'
        },
        storyThumbnail:Post1a,
        story:[
            {
            id:1,
            type:'image',
            source:Post1a,
            time:'1h'
            },
        ] 
    },
    {
        storyIndex:10,
        userProfile:{
            username:'jessie_franklin',
            profilePicture:'https://randomuser.me/api/portraits/med/men/80.jpg',
        },
        storyThumbnail:Post1a,
        story:[
            {
            id:1,
            type:'image',
            source:Post1a,
            time:'19h'
            },
        ] 
    }

]

export {
    StoryData,
    userStory
}